name: Build docker image

on: [push]

jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        elixir: ["1.12.3"]
        erlang: ["23.3"]
        ubuntu: ["20.04", "22.04"]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build and Push Docker image
        run: |
          python build.py \
            --elixir ${{ matrix.elixir }} \
            --erlang ${{ matrix.erlang }} \
            --ubuntu ${{ matrix.ubuntu }} \
            --repository ghcr.io/${{ github.repository_owner }} \
            --test \
            ${{ github.ref == 'refs/heads/develop' && '--push' || '' }}
